### ISSUE TITLE
Install error Windows 7 32bit

### ISSUE THREAD

**Issue by robertlagrant** [nwcell/psycopg2-windows#5]
Pip works in general, but this doesn't seem to work:

(venv) C:\rob\djangotest>pip install git+https://github.com/nwcell/psycopg2-windows.git@win32-py34#egg=psycopg2
Downloading/unpacking psycopg2 from git+https://github.com/nwcell/psycopg2-windows.git@win32-py34
Cleaning up...
Exception:
Traceback (most recent call last):
  File "C:\rob\Python34\lib\shutil.py", line 370, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'C:\Users\rgrant\AppData\Local\Temp\pip_build_RGRANT\psycopg2\.git\objects\pack\pack-6d3b0935968841c7fd3ba9ffabefdf24b0836531.idx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\rob\Python34\lib\site-packages\pip\basecommand.py", line 122, in main

```
status = self.run(options, args)
```

  File "C:\rob\Python34\lib\site-packages\pip\commands\install.py", line 278, in
 run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundl
e=self.bundle)
  File "C:\rob\Python34\lib\site-packages\pip\req.py", line 1197, in prepare_fil
es
    do_download,
  File "C:\rob\Python34\lib\site-packages\pip\req.py", line 1360, in unpack_url
    unpack_vcs_link(link, loc, only_download)
  File "C:\rob\Python34\lib\site-packages\pip\download.py", line 344, in unpack_
vcs_link
    vcs_backend.unpack(location)
  File "C:\rob\Python34\lib\site-packages\pip\vcs__init__.py", line 239, in unp
ack
    rmtree(location)
  File "C:\rob\Python34\lib\site-packages\pip\util.py", line 43, in rmtree
    onerror=rmtree_errorhandler)
  File "C:\rob\Python34\lib\shutil.py", line 477, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\rob\Python34\lib\shutil.py", line 367, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\rob\Python34\lib\shutil.py", line 367, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\rob\Python34\lib\shutil.py", line 367, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\rob\Python34\lib\shutil.py", line 372, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\rob\Python34\lib\site-packages\pip\util.py", line 53, in rmtree_error
handler
    (exctype is PermissionError and value.args[3] == 5) #python3.3
IndexError: tuple index out of range

Storing debug log for failure in C:\Users\rgrant\pip\pip.log

**Comment by vsable** [comment]
I have the same issue on windows 8 64bit Anaconda distribution of python 3.4

Exception:
Traceback (most recent call last):
  File "D:\Anaconda3\lib\shutil.py", line 370, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'C:\Users\Vivek\AppData\Local\Temp\pip_build_Vivek\psycopg2\.git\objects\p
ack\tmp_pack_3F98Qb'

**Comment by philliproso** [comment]
I am having the same problem. Anyone had any luck
