### ISSUE TITLE
Installation OK, error during cleanup

### ISSUE THREAD

**Issue by gimmi** [nwcell/psycopg2-windows#8]
The installation went OK, but i got an error during cleanup phase. Here is the output of the installation:

```
(venv) C:\Users\ggherardi\Sources\heroku-python-bottle>pip install git+https://github.com/nwcell/psycopg2-windows.git@win32-py34#egg=psycopg2
Downloading/unpacking psycopg2 from git+https://github.com/nwcell/psycopg2-windows.git@win32-py34
  Cloning https://github.com/nwcell/psycopg2-windows.git (to win32-py34) to c:\users\ggherardi\sources\heroku-python-bottle\venv\build\psycopg2
  Running setup.py (path:C:\Users\ggherardi\Sources\heroku-python-bottle\venv\build\psycopg2\setup.py) egg_info for package psycopg2
    C:\Python34\lib\distutils\dist.py:260: UserWarning: Unknown distribution option: 'summary'
      warnings.warn(msg)

Installing collected packages: psycopg2
  Running setup.py install for psycopg2
    C:\Python34\lib\distutils\dist.py:260: UserWarning: Unknown distribution option: 'summary'
      warnings.warn(msg)

Successfully installed psycopg2
Cleaning up...
  Exception:
Traceback (most recent call last):
  File "C:\Python34\lib\shutil.py", line 370, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\ggherardi\\Sources\\heroku-python-bottle\\venv\\build\\psycopg2\\.git\\objects\\pack\\pack-be4d3da4a06b4c9ec4c06040dbf6685eeccca068.idx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ggherardi\Sources\heroku-python-bottle\venv\lib\site-packages\pip\basecommand.py", line 122, in main
    status = self.run(options, args)
  File "C:\Users\ggherardi\Sources\heroku-python-bottle\venv\lib\site-packages\pip\commands\install.py", line 302, in run
    requirement_set.cleanup_files(bundle=self.bundle)
  File "C:\Users\ggherardi\Sources\heroku-python-bottle\venv\lib\site-packages\pip\req.py", line 1333, in cleanup_files
    rmtree(dir)
  File "C:\Users\ggherardi\Sources\heroku-python-bottle\venv\lib\site-packages\pip\util.py", line 43, in rmtree
    onerror=rmtree_errorhandler)
  File "C:\Python34\lib\shutil.py", line 477, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Python34\lib\shutil.py", line 367, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Python34\lib\shutil.py", line 367, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Python34\lib\shutil.py", line 367, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Python34\lib\shutil.py", line 367, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Python34\lib\shutil.py", line 372, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\ggherardi\Sources\heroku-python-bottle\venv\lib\site-packages\pip\util.py", line 53, in rmtree_errorhandler
    (exctype is PermissionError and value.args[3] == 5) #python3.3
IndexError: tuple index out of range

  Storing debug log for failure in C:\Users\ggherardi\pip\pip.log
```

and here is the contento of the mentioned `C:\Users\ggherardi\pip\pip.log` file:

```
------------------------------------------------------------
C:\Users\ggherardi\Sources\heroku-python-bottle\venv\Scripts\pip run on 12/30/14 14:22:13
Downloading/unpacking psycopg2 from git+https://github.com/nwcell/psycopg2-windows.git@win32-py34
  Cloning https://github.com/nwcell/psycopg2-windows.git (to win32-py34) to c:\users\ggherardi\sources\heroku-python-bottle\venv\build\psycopg2
  Found command 'git' at 'C:\\Program Files (x86)\\Git\\cmd\\git.exe'
  Running command "C:\Program Files (x86)\Git\cmd\git.exe" clone -q https://github.com/nwcell/psycopg2-windows.git C:\Users\ggherardi\Sources\heroku-python-bottle\venv\build\psycopg2
  Running command "C:\Program Files (x86)\Git\cmd\git.exe" show-ref
  5698844286001962f3eeeab58164301898ef48e9 refs/heads/master
  5698844286001962f3eeeab58164301898ef48e9 refs/remotes/origin/HEAD
  5698844286001962f3eeeab58164301898ef48e9 refs/remotes/origin/master
  4200a3866f92b4b7bb07701f8f4d0e221f006d72 refs/remotes/origin/win32-py25
  d988177bec98ff1aa5aa593ab3fed876e30c303a refs/remotes/origin/win32-py26
  e341ef8e3b93daf670a99baef05a4b3bcc729ce6 refs/remotes/origin/win32-py27
  47a1b79f23f17e067b3a3b444c0070d4b6dee5d5 refs/remotes/origin/win32-py32
  c54c13f6b156b9965d9876bd9fd28428d0a10f1f refs/remotes/origin/win32-py33
  02d0abb3dc219d8fd5e141fffcb4e5ce0caf680e refs/remotes/origin/win32-py34
  2ee452cfe79731861e159341a484ddab4b686f7e refs/remotes/origin/win64-py26
  924849520a04d00895986e9161f945330ceb190d refs/remotes/origin/win64-py27
  691710e8efc39d26fef6cbc693f2a74a4f5fc9a8 refs/remotes/origin/win64-py32
  9e81d60836eb6b892781943d7277fbafaae6300d refs/remotes/origin/win64-py33
  4039d982152492453abdfb72d0054230fcb42c30 refs/remotes/origin/win64-py34
  e476d8bdc15e862325752da46f9d23a76411a940 refs/tags/0.1.0
  ef3b15d8ed1633c9df76a0fbb87503caf4bcce3a refs/tags/win32-py25-psycopg2-252
  9c16b6cf7479394178d5d32f7b4a104c6d32245e refs/tags/win32-py25-psycopg2-253
  034c30f84b441a0cc2d6140ed385ccdfcd507acc refs/tags/win32-py26-psycopg2-252
  51d9bcfbfe4a99639c16dd9eff5a0fca8abf6761 refs/tags/win32-py26-psycopg2-253
  6356f08b3498d8674343937084bd62da79b5563b refs/tags/win32-py27-psycopg2-252
  836416feeebc02283315e30a8f7bea66fa599451 refs/tags/win32-py27-psycopg2-253
  7db1dae9194e9ca15df2f51672d785dfa9519088 refs/tags/win32-py32-psycopg2-252
  8690475c521c22b52a57933fcc2b05d42a2439b1 refs/tags/win32-py32-psycopg2-253
  c65306a339a528215f25d2d5faba204aef894fd3 refs/tags/win32-py33-psycopg2-252
  8f59901bc7efdc0061f28a2e1f90e98e23bd5d3a refs/tags/win32-py33-psycopg2-253
  ed9ef6dc1eeb1526eac6b54fee2a618f828b7482 refs/tags/win32-py34-psycopg2-253
  1262d00c4dcbcb98619fac12d8688d9c110afbb7 refs/tags/win62-py26-psycopg2-252
  9ed8ef7a9fac4de21774c6442d1cc8d04496dc9e refs/tags/win64-py26-psycopg2-253
  27bd71b9cf4654096d1b6538e147c36285d8d40e refs/tags/win64-py27-psycopg2-252
  ea4d35219b5ef93df7bc3f4e40f0aad4d5adb57c refs/tags/win64-py27-psycopg2-253
  cbd16f3f06e57f0c4d17db79eb11226f0bea5643 refs/tags/win64-py32-psycopg2-252
  5280fc7f5f966ba5a5be05d77f7ec010dab935e9 refs/tags/win64-py32-psycopg2-253
  874c0d8c274ea02b405c0fc42c409932dab8cbb3 refs/tags/win64-py33-psycopg2-252
  119902cd91ac173166c1af6fa6b77b721f82e6db refs/tags/win64-py33-psycopg2-253
  a3517ae38f1aef2faead9475b008064b85b3f045 refs/tags/win64-py34-psycopg2-253
  Running command "C:\Program Files (x86)\Git\cmd\git.exe" rev-parse HEAD
  5698844286001962f3eeeab58164301898ef48e9
  Running command "C:\Program Files (x86)\Git\cmd\git.exe" checkout -q 02d0abb3dc219d8fd5e141fffcb4e5ce0caf680e
  Running setup.py (path:C:\Users\ggherardi\Sources\heroku-python-bottle\venv\build\psycopg2\setup.py) egg_info for package psycopg2
    running egg_info
    creating pip-egg-info\psycopg2.egg-info
    writing top-level names to pip-egg-info\psycopg2.egg-info\top_level.txt
    writing dependency_links to pip-egg-info\psycopg2.egg-info\dependency_links.txt
    writing pip-egg-info\psycopg2.egg-info\PKG-INFO
    writing manifest file 'pip-egg-info\psycopg2.egg-info\SOURCES.txt'
    C:\Python34\lib\distutils\dist.py:260: UserWarning: Unknown distribution option: 'summary'
      warnings.warn(msg)
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'pip-egg-info\psycopg2.egg-info\SOURCES.txt'
    writing manifest file 'pip-egg-info\psycopg2.egg-info\SOURCES.txt'
  Source in c:\users\ggherardi\sources\heroku-python-bottle\venv\build\psycopg2 has version 2.5.2, which satisfies requirement psycopg2 from git+https://github.com/nwcell/psycopg2-windows.git@win32-py34
Installing collected packages: psycopg2
  Running setup.py install for psycopg2
    Running command C:\Users\ggherardi\Sources\heroku-python-bottle\venv\Scripts\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\ggherardi\\Sources\\heroku-python-bottle\\venv\\build\\psycopg2\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\GGHERA~1\AppData\Local\Temp\pip-y92msfa6-record\install-record.txt --single-version-externally-managed --compile --install-headers C:\Users\ggherardi\Sources\heroku-python-bottle\venv\include\site\python3.4
    running install
    running build
    running install_egg_info
    running egg_info
    creating psycopg2.egg-info
    writing top-level names to psycopg2.egg-info\top_level.txt
    writing psycopg2.egg-info\PKG-INFO
    writing dependency_links to psycopg2.egg-info\dependency_links.txt
    writing manifest file 'psycopg2.egg-info\SOURCES.txt'
    C:\Python34\lib\distutils\dist.py:260: UserWarning: Unknown distribution option: 'summary'
      warnings.warn(msg)
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'psycopg2.egg-info\SOURCES.txt'
    writing manifest file 'psycopg2.egg-info\SOURCES.txt'
    Copying psycopg2.egg-info to C:\Users\ggherardi\Sources\heroku-python-bottle\venv\Lib\site-packages\psycopg2-2.5.2-py3.4.egg-info
    running install_scripts
    writing list of installed files to 'C:\Users\GGHERA~1\AppData\Local\Temp\pip-y92msfa6-record\install-record.txt'
Successfully installed psycopg2
Cleaning up...
  Removing temporary dir C:\Users\ggherardi\Sources\heroku-python-bottle\venv\build...
  Exception:
Traceback (most recent call last):
  File "C:\Python34\lib\shutil.py", line 370, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\ggherardi\\Sources\\heroku-python-bottle\\venv\\build\\psycopg2\\.git\\objects\\pack\\pack-be4d3da4a06b4c9ec4c06040dbf6685eeccca068.idx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ggherardi\Sources\heroku-python-bottle\venv\lib\site-packages\pip\basecommand.py", line 122, in main
    status = self.run(options, args)
  File "C:\Users\ggherardi\Sources\heroku-python-bottle\venv\lib\site-packages\pip\commands\install.py", line 302, in run
    requirement_set.cleanup_files(bundle=self.bundle)
  File "C:\Users\ggherardi\Sources\heroku-python-bottle\venv\lib\site-packages\pip\req.py", line 1333, in cleanup_files
    rmtree(dir)
  File "C:\Users\ggherardi\Sources\heroku-python-bottle\venv\lib\site-packages\pip\util.py", line 43, in rmtree
    onerror=rmtree_errorhandler)
  File "C:\Python34\lib\shutil.py", line 477, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Python34\lib\shutil.py", line 367, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Python34\lib\shutil.py", line 367, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Python34\lib\shutil.py", line 367, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Python34\lib\shutil.py", line 367, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Python34\lib\shutil.py", line 372, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\ggherardi\Sources\heroku-python-bottle\venv\lib\site-packages\pip\util.py", line 53, in rmtree_errorhandler
    (exctype is PermissionError and value.args[3] == 5) #python3.3
IndexError: tuple index out of range
```

**Comment by autoferrit** [comment]
I seem to be getting the same issue here. I am on windwos 8.1 x64. here is my console

```
λ pip install git+https://github.com/nwcell/psycopg2-windows.git@win64-py34#egg=psycopg2                          
Downloading/unpacking psycopg2 from git+https://github.com/nwcell/psycopg2-windows.git@win64-py34                 
  Cloning https://github.com/nwcell/psycopg2-windows.git (to win64-py34) to z:\www\apps\sites\skiftcreative\greybe
ard\env\build\psycopg2                                                                                            
  Running setup.py (path:Z:\www\apps\sites\skiftcreative\greybeard\env\build\psycopg2\setup.py) egg_info for packa
ge psycopg2                                                                                                       
    C:\Python34\Lib\distutils\dist.py:260: UserWarning: Unknown distribution option: 'summary'                    
      warnings.warn(msg)                                                                                          

Installing collected packages: psycopg2                                                                           
  Running setup.py install for psycopg2                                                                           
    C:\Python34\Lib\distutils\dist.py:260: UserWarning: Unknown distribution option: 'summary'                    
      warnings.warn(msg)                                                                                          

Successfully installed psycopg2                                                                                   
Cleaning up...                                                                                                    
  Exception:                                                                                                      
Traceback (most recent call last):                                                                                
  File "Z:\www\apps\sites\skiftcreative\greybeard\env\lib\shutil.py", line 370, in _rmtree_unsafe                 
    os.unlink(fullname)                                                                                           
PermissionError: [WinError 5] Access is denied: 'Z:\\www\\apps\\sites\\skiftcreative\\greybeard\\env\\build\\psyco
pg2\\.git\\objects\\pack\\pack-be4d3da4a06b4c9ec4c06040dbf6685eeccca068.idx'                                      

During handling of the above exception, another exception occurred:                                               

Traceback (most recent call last):                                                                                
  File "Z:\www\apps\sites\skiftcreative\greybeard\env\lib\site-packages\pip\basecommand.py", line 122, in main    
    status = self.run(options, args)                                                                              
  File "Z:\www\apps\sites\skiftcreative\greybeard\env\lib\site-packages\pip\commands\install.py", line 302, in run

    requirement_set.cleanup_files(bundle=self.bundle)                                                             
  File "Z:\www\apps\sites\skiftcreative\greybeard\env\lib\site-packages\pip\req.py", line 1333, in cleanup_files  
    rmtree(dir)                                                                                                   
  File "Z:\www\apps\sites\skiftcreative\greybeard\env\lib\site-packages\pip\util.py", line 43, in rmtree          
    onerror=rmtree_errorhandler)                                                                                  
  File "Z:\www\apps\sites\skiftcreative\greybeard\env\lib\shutil.py", line 477, in rmtree                         
    return _rmtree_unsafe(path, onerror)                                                                          
  File "Z:\www\apps\sites\skiftcreative\greybeard\env\lib\shutil.py", line 367, in _rmtree_unsafe                 
    _rmtree_unsafe(fullname, onerror)                                                                             
  File "Z:\www\apps\sites\skiftcreative\greybeard\env\lib\shutil.py", line 367, in _rmtree_unsafe                 
    _rmtree_unsafe(fullname, onerror)                                                                             
  File "Z:\www\apps\sites\skiftcreative\greybeard\env\lib\shutil.py", line 367, in _rmtree_unsafe                 
    _rmtree_unsafe(fullname, onerror)                                                                             
  File "Z:\www\apps\sites\skiftcreative\greybeard\env\lib\shutil.py", line 367, in _rmtree_unsafe                 
    _rmtree_unsafe(fullname, onerror)                                                                             
  File "Z:\www\apps\sites\skiftcreative\greybeard\env\lib\shutil.py", line 372, in _rmtree_unsafe                 
    onerror(os.unlink, fullname, sys.exc_info())                                                                  
  File "Z:\www\apps\sites\skiftcreative\greybeard\env\lib\site-packages\pip\util.py", line 53, in rmtree_errorhand
ler                                                                                                               
    (exctype is PermissionError and value.args[3] == 5) #python3.3                                                
IndexError: tuple index out of range                                                                              

  Storing debug log for failure in C:\Users\Shawn\pip\pip.log                                                                                                                      
```

and my debug.log

```
Z:\www\apps\sites\skiftcreative\greybeard\env\Scripts\pip run on 01/21/15 22:59:15                                
Downloading/unpacking psycopg2 from git+https://github.com/nwcell/psycopg2-windows.git@win64-py34                 
  Cloning https://github.com/nwcell/psycopg2-windows.git (to win64-py34) to z:\www\apps\sites\skiftcreative\greybe
ard\env\build\psycopg2                                                                                            
  Found command 'git' at 'C:\\Program Files\\cmder\\vendor\\msysgit\\bin\\git.exe'                                
  Running command "C:\Program Files\cmder\vendor\msysgit\bin\git.exe" clone -q https://github.com/nwcell/psycopg2-
windows.git Z:\www\apps\sites\skiftcreative\greybeard\env\build\psycopg2                                          
  Running command "C:\Program Files\cmder\vendor\msysgit\bin\git.exe" show-ref                                    
  5698844286001962f3eeeab58164301898ef48e9 refs/heads/master                                                      
  5698844286001962f3eeeab58164301898ef48e9 refs/remotes/origin/HEAD                                               
  5698844286001962f3eeeab58164301898ef48e9 refs/remotes/origin/master                                             
  4200a3866f92b4b7bb07701f8f4d0e221f006d72 refs/remotes/origin/win32-py25                                         
  d988177bec98ff1aa5aa593ab3fed876e30c303a refs/remotes/origin/win32-py26                                         
  e341ef8e3b93daf670a99baef05a4b3bcc729ce6 refs/remotes/origin/win32-py27                                         
  47a1b79f23f17e067b3a3b444c0070d4b6dee5d5 refs/remotes/origin/win32-py32                                         
  c54c13f6b156b9965d9876bd9fd28428d0a10f1f refs/remotes/origin/win32-py33                                         
  02d0abb3dc219d8fd5e141fffcb4e5ce0caf680e refs/remotes/origin/win32-py34                                         
  2ee452cfe79731861e159341a484ddab4b686f7e refs/remotes/origin/win64-py26                                         
  924849520a04d00895986e9161f945330ceb190d refs/remotes/origin/win64-py27                                         
  691710e8efc39d26fef6cbc693f2a74a4f5fc9a8 refs/remotes/origin/win64-py32                                         
  9e81d60836eb6b892781943d7277fbafaae6300d refs/remotes/origin/win64-py33                                         
  4039d982152492453abdfb72d0054230fcb42c30 refs/remotes/origin/win64-py34                                         
  e476d8bdc15e862325752da46f9d23a76411a940 refs/tags/0.1.0                                                        
  ef3b15d8ed1633c9df76a0fbb87503caf4bcce3a refs/tags/win32-py25-psycopg2-252                                      
  9c16b6cf7479394178d5d32f7b4a104c6d32245e refs/tags/win32-py25-psycopg2-253                                      
  034c30f84b441a0cc2d6140ed385ccdfcd507acc refs/tags/win32-py26-psycopg2-252                                      
  51d9bcfbfe4a99639c16dd9eff5a0fca8abf6761 refs/tags/win32-py26-psycopg2-253                                      
  6356f08b3498d8674343937084bd62da79b5563b refs/tags/win32-py27-psycopg2-252                                      
  836416feeebc02283315e30a8f7bea66fa599451 refs/tags/win32-py27-psycopg2-253                                      
  7db1dae9194e9ca15df2f51672d785dfa9519088 refs/tags/win32-py32-psycopg2-252                                      
  8690475c521c22b52a57933fcc2b05d42a2439b1 refs/tags/win32-py32-psycopg2-253                                      
  c65306a339a528215f25d2d5faba204aef894fd3 refs/tags/win32-py33-psycopg2-252                                      
  8f59901bc7efdc0061f28a2e1f90e98e23bd5d3a refs/tags/win32-py33-psycopg2-253                                      
  ed9ef6dc1eeb1526eac6b54fee2a618f828b7482 refs/tags/win32-py34-psycopg2-253                                      
  1262d00c4dcbcb98619fac12d8688d9c110afbb7 refs/tags/win62-py26-psycopg2-252                                      
  9ed8ef7a9fac4de21774c6442d1cc8d04496dc9e refs/tags/win64-py26-psycopg2-253                                      
  27bd71b9cf4654096d1b6538e147c36285d8d40e refs/tags/win64-py27-psycopg2-252                                      
  ea4d35219b5ef93df7bc3f4e40f0aad4d5adb57c refs/tags/win64-py27-psycopg2-253                                      
  cbd16f3f06e57f0c4d17db79eb11226f0bea5643 refs/tags/win64-py32-psycopg2-252                                      
  5280fc7f5f966ba5a5be05d77f7ec010dab935e9 refs/tags/win64-py32-psycopg2-253                                      
  874c0d8c274ea02b405c0fc42c409932dab8cbb3 refs/tags/win64-py33-psycopg2-252                                      
  119902cd91ac173166c1af6fa6b77b721f82e6db refs/tags/win64-py33-psycopg2-253                                      
  a3517ae38f1aef2faead9475b008064b85b3f045 refs/tags/win64-py34-psycopg2-253                                      
  Running command "C:\Program Files\cmder\vendor\msysgit\bin\git.exe" rev-parse HEAD                              
  5698844286001962f3eeeab58164301898ef48e9                                                                        
  Running command "C:\Program Files\cmder\vendor\msysgit\bin\git.exe" checkout -q 4039d982152492453abdfb72d0054230
fcb42c30                                                                                                          
  Running setup.py (path:Z:\www\apps\sites\skiftcreative\greybeard\env\build\psycopg2\setup.py) egg_info for packa
ge psycopg2                                                                                                       
    running egg_info                                                                                              
    creating pip-egg-info\psycopg2.egg-info                                                                       
    writing top-level names to pip-egg-info\psycopg2.egg-info\top_level.txt                                       
    writing pip-egg-info\psycopg2.egg-info\PKG-INFO                                                               
    writing dependency_links to pip-egg-info\psycopg2.egg-info\dependency_links.txt                               
    writing manifest file 'pip-egg-info\psycopg2.egg-info\SOURCES.txt'                                            
    C:\Python34\Lib\distutils\dist.py:260: UserWarning: Unknown distribution option: 'summary'                    
      warnings.warn(msg)                                                                                          
    warning: manifest_maker: standard file '-c' not found                                                         

    reading manifest file 'pip-egg-info\psycopg2.egg-info\SOURCES.txt'                                            
    writing manifest file 'pip-egg-info\psycopg2.egg-info\SOURCES.txt'                                            
  Source in z:\www\apps\sites\skiftcreative\greybeard\env\build\psycopg2 has version 2.5.2, which satisfies requir
ement psycopg2 from git+https://github.com/nwcell/psycopg2-windows.git@win64-py34                                 
Installing collected packages: psycopg2                                                                           
  Running setup.py install for psycopg2                                                                           
    Running command Z:\www\apps\sites\skiftcreative\greybeard\env\Scripts\python.exe -c "import setuptools, tokeni
ze;__file__='Z:\\www\\apps\\sites\\skiftcreative\\greybeard\\env\\build\\psycopg2\\setup.py';exec(compile(getattr(
tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\Shaw
n\AppData\Local\Temp\pip-rr95ndfj-record\install-record.txt --single-version-externally-managed --compile --instal
l-headers Z:\www\apps\sites\skiftcreative\greybeard\env\include\site\python3.4                                    
    running install                                                                                               
    running build                                                                                                 
    running install_egg_info                                                                                      
    running egg_info                                                                                              
    creating psycopg2.egg-info                                                                                    
    writing top-level names to psycopg2.egg-info\top_level.txt                                                    
    writing dependency_links to psycopg2.egg-info\dependency_links.txt                                            
    writing psycopg2.egg-info\PKG-INFO                                                                            
    writing manifest file 'psycopg2.egg-info\SOURCES.txt'                                                         
    C:\Python34\Lib\distutils\dist.py:260: UserWarning: Unknown distribution option: 'summary'                    
      warnings.warn(msg)                                                                                          
    warning: manifest_maker: standard file '-c' not found                                                         

    reading manifest file 'psycopg2.egg-info\SOURCES.txt'                                                         
    writing manifest file 'psycopg2.egg-info\SOURCES.txt'                                                         
    Copying psycopg2.egg-info to Z:\www\apps\sites\skiftcreative\greybeard\env\Lib\site-packages\psycopg2-2.5.2-py
3.4.egg-info                                                                                                      
    running install_scripts                                                                                       
    writing list of installed files to 'C:\Users\Shawn\AppData\Local\Temp\pip-rr95ndfj-record\install-record.txt' 
Successfully installed psycopg2                                                                                   
Cleaning up...                                                                                                    
  Removing temporary dir Z:\www\apps\sites\skiftcreative\greybeard\env\build...                                   
  Exception:                                                                                                      
Traceback (most recent call last):                                                                                
  File "Z:\www\apps\sites\skiftcreative\greybeard\env\lib\shutil.py", line 370, in _rmtree_unsafe                 
    os.unlink(fullname)                                                                                           
PermissionError: [WinError 5] Access is denied: 'Z:\\www\\apps\\sites\\skiftcreative\\greybeard\\env\\build\\psyco
pg2\\.git\\objects\\pack\\pack-be4d3da4a06b4c9ec4c06040dbf6685eeccca068.idx'                                      

During handling of the above exception, another exception occurred:                                               

Traceback (most recent call last):                                                                                
  File "Z:\www\apps\sites\skiftcreative\greybeard\env\lib\site-packages\pip\basecommand.py", line 122, in main    
    status = self.run(options, args)                                                                              
  File "Z:\www\apps\sites\skiftcreative\greybeard\env\lib\site-packages\pip\commands\install.py", line 302, in run

    requirement_set.cleanup_files(bundle=self.bundle)                                                             
  File "Z:\www\apps\sites\skiftcreative\greybeard\env\lib\site-packages\pip\req.py", line 1333, in cleanup_files  
    rmtree(dir)                                                                                                   
  File "Z:\www\apps\sites\skiftcreative\greybeard\env\lib\site-packages\pip\util.py", line 43, in rmtree          
    onerror=rmtree_errorhandler)                                                                                  
  File "Z:\www\apps\sites\skiftcreative\greybeard\env\lib\shutil.py", line 477, in rmtree                         
    return _rmtree_unsafe(path, onerror)                                                                          
  File "Z:\www\apps\sites\skiftcreative\greybeard\env\lib\shutil.py", line 367, in _rmtree_unsafe                 
    _rmtree_unsafe(fullname, onerror)                                                                             
  File "Z:\www\apps\sites\skiftcreative\greybeard\env\lib\shutil.py", line 367, in _rmtree_unsafe                 
    _rmtree_unsafe(fullname, onerror)                                                                             
  File "Z:\www\apps\sites\skiftcreative\greybeard\env\lib\shutil.py", line 367, in _rmtree_unsafe                 
    _rmtree_unsafe(fullname, onerror)                                                                             
  File "Z:\www\apps\sites\skiftcreative\greybeard\env\lib\shutil.py", line 367, in _rmtree_unsafe                 
    _rmtree_unsafe(fullname, onerror)                                                                             
  File "Z:\www\apps\sites\skiftcreative\greybeard\env\lib\shutil.py", line 372, in _rmtree_unsafe                 
    onerror(os.unlink, fullname, sys.exc_info())                                                                  
  File "Z:\www\apps\sites\skiftcreative\greybeard\env\lib\site-packages\pip\util.py", line 53, in rmtree_errorhand
ler                                                                                                               
    (exctype is PermissionError and value.args[3] == 5) #python3.3                                                
IndexError: tuple index out of range                                                                              

```

**Comment by ghost** [comment]
Similar issue on Windows. Running as administrator didn't help.

**Comment by lindsay-stevens** [comment]
I had same error with python 3.4.1 on Win7 64bit, trying to install the @win32-py34 branch with git bash into a virtual environment. I upgraded to Python to 3.4.3 and the problem went away. 

Well, there is still a warning that "summary" is not a distribution option but that is no big deal.
